sns updated

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -206,13 +206,6 @@ jobs:
       run: |
         aws ec2 describe-security-groups --group-ids ${{ secrets.DB_SECURITY_GROUP_ID }} --query "SecurityGroups[0].IpPermissions"
 
-    # DNS Resolution Check
-    - name: DNS Resolution for RDS Endpoint
-      run: |
-        nslookup ${{ secrets.RDS_HOST }}
-        ping -c 4 ${{ secrets.RDS_HOST }}
-
-
     - name: Update Auto Scaling Group to Use New Launch Template Version (Demo)
       run: |
         aws autoscaling update-auto-scaling-group \
@@ -228,6 +221,16 @@ jobs:
           --preferences '{"MinHealthyPercentage": 100}' \
           --query 'InstanceRefreshId' --output text)
         echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV
+
+    # DNS Resolution Check
+    - name: DNS Resolution for RDS Endpoint
+      run: |
+        nslookup ${{ secrets.RDS_HOST }}
+
+    # Port Connectivity Check (instead of ping)
+    - name: Check MySQL Port Connectivity on RDS
+      run: |
+        telnet ${{ secrets.RDS_HOST }} 3306 || echo "Error: Cannot connect to RDS on port 3306"
 
     - name: Wait for Instance Refresh Completion (Demo)
       run: |
